CUDA_VISIBLE_DEVICES=0 python main.py \
    --model 'wideres' \
    --name 'adv.pth' \
    --dataset 'cifar10' \
    --datapath 'data' \
    --attack 'FGSM'\
    --batch_size 64 \
    --attack_steps 20 \
    --attack_lr 2 \
    --viz_result \
    --random_init